services:
  server:
    build: ./backend
    container_name: server
    ports:
      - "5000:5000"

  client:
    build: ./frontend/online-shopping-prediction
    container_name: client
    ports:
      - "4173:4173"
    stdin_open: true
    tty: true